### PR TITLE
 #163386490: improve UI/UX on all profile pages

### PR DESCRIPTION
**Pull request by vic3king**
#### What does this PR do?
Users page should have improved UI/UX

#### Description of Task to be completed?
- update UI/UX on admin-profile.html
- update UI/UX on citizens.html
- update UI/UX on politicians.html
#### How should this be manually tested?
 **visit below links to view the updated pages**  
- https://vic3king.github.io/politico/admin-profile.html
- https://vic3king.github.io/politico/citizens.htm
- https://vic3king.github.io/politico/politicians.html

#### What are the relevant pivotal tracker stories?
[Story-ID](https://www.pivotaltracker.com/n/projects/2238799/stories/163386490)

#### Questions:

[delivers #163386490]

### CODE REVIEW

**Comment by JCanaks** [comment]
Great work so far. A few feedbacks
- Put a demarcation between the profile and office positions
- Work on your UI colours
- Increase the font on the positions card and remove the border-radius on the cards and the buttons
- Change the political parties list to cards
- Improve your profile photo placeholder
- Work on the text underneath your profile photo
- Improve the card look for your `candidates` list add an image and arrange the text beneath it
- Utilize the spaces on your pages
- Make the form information for each page come directly under the where it is referenced 
- For the `citizens.html page`Please reduce the button size and make them fit under the card.

**Comment by JCanaks** [comment]
The PT story title should be the description for your PR title

**Comment by JCanaks** [comment]
@vic3king Pls follow the convention for branch naming 
will do, and will also rename the branches with wrong naming

**Comment by vic3king** [comment]
> The PT story title should be the description for your PR title

noted thank you

**Comment by JCanaks** [comment]
Great work. The color choices are much better. This is a far cry from your first output. Just a few feedbacks:
- Bolden the labels (only the labels) in the profile section
- increase the font size of `Open Positions and Political parties` in pages where they appear and reduce the space above `political parties`in the admin-profile page
- Also align the pagination for `Political Parties` in the admin-profile page
-In the admin-profile page and citizens page you have two home labels pls remove one and capitalize the first letter of each word in the navigation bar
- change the results button in the citizens page to `Election Results` to make it more descriptive

**Pull request merged**
